### ISSUE TITLE
Backslash bug

### ISSUE THREAD

**Issue by monoblaine** [sindresorhus/to-single-quotes#11]
Found a strange bug while trying to convert the double-quotes in a js file to single-quotes:

This line:

```js
var foo = "\\";
```

is converted into this:

```js
var foo = '\';
```

Example repo here:
https://github.com/monoblaine/to-single-quotes-backslash-bug

**Comment by AuthorProxy** [comment]
https://github.com/jscs-dev/node-jscs/issues/2172
