### ISSUE TITLE
Make `to-double-quotes` depend on this module

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/to-single-quotes#15]
So [`to-double-quotes`](https://github.com/sindresorhus/to-double-quotes) can reuse the code here. No point in duplicating it.

Need to add support for choosing the quote to transform to and expose an internal method that `to-double-quotes` can use.

I'm thinking:

```js
function transform(input, toSingleQuotes) {
	// Main code here
}

module.exports = input => transform(input, true);

module.exports._transform = transform;
```

That way `to-double-quotes` can use `_transform()`.

---

// @ruipneves In case you're interested.

**Comment by ruipneves** [comment]
@sindresorhus I'm on it!
