### ISSUE TITLE
Slash issue

### ISSUE THREAD

**Issue by markelog** [sindresorhus/to-single-quotes#6]
This `" '1\\'2' "` will be transformed into this `' \'1\\'2\' '` which is syntax violation.

This issue blocks https://github.com/jscs-dev/node-jscs/pull/1415

**Comment by sindresorhus** [comment]
Can you try out https://github.com/sindresorhus/to-single-quotes/commit/5d2fd2b90ad0e371082d35a8197cbc360a28642f ?
