### ISSUE TITLE
Cannot handle inner double quotes

### ISSUE THREAD

**Issue by IanVS** [sindresorhus/to-single-quotes#9]
Converting this string:

``` js
'bar "foo" baz'
```

Results in:

``` js
'bar 'foo' baz'
```

But it should be:

``` js
'bar \'foo\' baz'
```

In other words, this test case will fail:

``` js
t.is(fn('\'bar "foo" baz\''), '\'bar \\\'foo\\\' baz\'');
```

**Comment by sindresorhus** [comment]
It can:

```js
t.is(fn('\'bar "foo" baz\''), '\'bar \'foo\' baz\'');
```

**Comment by IanVS** [comment]
Yes, but that is not a valid string. The inner single quotes should be escaped, right?

**Comment by sindresorhus** [comment]
How is it now a valid string? The above test passes fine.

**Comment by IanVS** [comment]
The assertion `'\'bar \'foo\' baz\''` is:

```js
'bar 'foo' baz'
```

Notice the unescaped single quotes around `foo`, causing it to become a variable reference.

I think the correct assertion is:

```js
'\'bar \\\'foo\\\' baz\''
```

Which is:

```js
'bar \'foo\' baz'
```

**Comment by sindresorhus** [comment]
Oh, yeah, you're absolutely right.

**Comment by sindresorhus** [comment]
Seems like this was fixed by https://github.com/sindresorhus/to-single-quotes/commit/7f203d0f6a25ab5e74911732b77de02f8dc7eae2
